#!/usr/bin/env bash
set -euo pipefail

# Clears log files generated by the local development services.
DEFAULT_LOG_DIRS=(
  "core/api/logs"
  "core/gui/logs"
  "core/transcoder/logs"
  "core/ingest/logs"
)

show_help() {
  cat <<'USAGE'
Usage: ./clear_logs.sh [log_dir ...]

Without arguments, clears the default log directories used by the API,
GUI, transcoder, and ingest services. Provide one or more
directories to override the defaults.
USAGE
}

if [[ $# -gt 0 ]]; then
  case "$1" in
    -h|--help)
      show_help
      exit 0
      ;;
    --)
      shift
      ;;
  esac
  LOG_DIRS=("$@")
else
  LOG_DIRS=("${DEFAULT_LOG_DIRS[@]}")
fi

if [[ ${#LOG_DIRS[@]} -eq 0 ]]; then
  echo "No log directories specified." >&2
  exit 1
fi

for log_dir in "${LOG_DIRS[@]}"; do
  if [[ ! -d "$log_dir" ]]; then
    echo "Skipping missing directory: $log_dir"
    continue
  fi

  has_contents=$(find "$log_dir" -mindepth 1 -print -quit)
  if [[ -z "$has_contents" ]]; then
    echo "Already clean: $log_dir"
    continue
  fi

  echo "Clearing: $log_dir"
  find "$log_dir" -mindepth 1 -type f -delete
  find "$log_dir" -mindepth 1 -type d -empty -delete
  echo "Cleared: $log_dir"

done

echo "Log cleanup complete."
