"""Configuration helpers for the transcoder microservice."""
from __future__ import annotations

import os
from typing import Any, Dict

from .constants import (
    DEFAULT_AUTO_KEYFRAMING,
    DEFAULT_BASENAME,
    DEFAULT_CELERY_AV_QUEUE,
    DEFAULT_CELERY_RESULT_BACKEND,
    DEFAULT_CELERY_TASK_TIMEOUT_SECONDS,
    DEFAULT_CORS_ORIGIN,
    DEFAULT_DEBUG_ENDPOINT_ENABLED,
    DEFAULT_INPUT,
    DEFAULT_OUTPUT,
    DEFAULT_PUBLISH_BASE_URL,
    DEFAULT_REDIS_URL,
    DEFAULT_STATUS_CHANNEL,
    DEFAULT_STATUS_HEARTBEAT_SECONDS,
    DEFAULT_STATUS_KEY,
    DEFAULT_STATUS_NAMESPACE,
    DEFAULT_STATUS_PREFIX,
    DEFAULT_STATUS_REDIS_URL,
    DEFAULT_STATUS_TTL_SECONDS,
)

__all__ = ["build_default_config"]


def build_default_config() -> Dict[str, Any]:
    """Return the base configuration mapping for the microservice."""

    cfg: Dict[str, Any] = {
        "TRANSCODER_INPUT": DEFAULT_INPUT,
        "TRANSCODER_OUTPUT": DEFAULT_OUTPUT,
        "TRANSCODER_OUTPUT_BASENAME": DEFAULT_BASENAME,
        "TRANSCODER_PUBLISH_BASE_URL": DEFAULT_PUBLISH_BASE_URL,
        "TRANSCODER_CORS_ORIGIN": DEFAULT_CORS_ORIGIN,
        "TRANSCODER_AUTO_KEYFRAMING": DEFAULT_AUTO_KEYFRAMING,
        "TRANSCODER_DEBUG_ENDPOINT_ENABLED": DEFAULT_DEBUG_ENDPOINT_ENABLED,
        "CELERY_BROKER_URL": DEFAULT_REDIS_URL,
        "CELERY_RESULT_BACKEND": DEFAULT_CELERY_RESULT_BACKEND,
        "CELERY_TASK_DEFAULT_QUEUE": DEFAULT_CELERY_AV_QUEUE,
        "CELERY_TRANSCODE_AV_QUEUE": DEFAULT_CELERY_AV_QUEUE,
        "CELERY_TASK_TIMEOUT_SECONDS": DEFAULT_CELERY_TASK_TIMEOUT_SECONDS,
        "TRANSCODER_INTERNAL_TOKEN": os.getenv("TRANSCODER_INTERNAL_TOKEN"),
        "TRANSCODER_STATUS_REDIS_URL": DEFAULT_STATUS_REDIS_URL,
        "TRANSCODER_STATUS_PREFIX": DEFAULT_STATUS_PREFIX,
        "TRANSCODER_STATUS_NAMESPACE": DEFAULT_STATUS_NAMESPACE,
        "TRANSCODER_STATUS_KEY": DEFAULT_STATUS_KEY,
        "TRANSCODER_STATUS_CHANNEL": DEFAULT_STATUS_CHANNEL,
        "TRANSCODER_STATUS_TTL_SECONDS": DEFAULT_STATUS_TTL_SECONDS,
        "TRANSCODER_STATUS_HEARTBEAT_SECONDS": DEFAULT_STATUS_HEARTBEAT_SECONDS,
    }
    return cfg
